# action.yml
name: 'Reproduce issue'
description: 'See project files for more details'
inputs:
  command:
    description: 'command to execute'
    required: true
    default: 'echo hello world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
