on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Reproduce issue
    steps:
      - uses: actions/checkout@v2
      - name: Run command in the failing docker image
        id: hello
        uses: gableroux/pylint-celery-setuptools-issue@v1
        with:
          command: |
            pip-compile --generate-hashes -o requirements.txt
            pip install -r requirements.txt
