on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Reproduce issue
    steps:
      - name: Run command in the failing docker image
        id: hello
        uses: gableroux/pylint-celery-setuptools-issue@v1
        with:
          command: pip install -r requirements.txt
