on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Reproduce issue
    steps:
      - uses: actions/checkout@v2
      - name: Generate requirements.txt
        uses: gableroux/pylint-celery-setuptools-issue@v1
        with:
          command: pip-compile --generate-hashes -o requirements.txt
      - name: Install requirements.txt
        uses: gableroux/pylint-celery-setuptools-issue@v1
        with:
          command: pip install -r requirements.txt
