on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Reproduce issue
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
      - run: pip install --upgrade pip
      - run: pip install pip-tools
      - run: pip-compile --generate-hashes -o requirements.txt
      - run: pip install -r requirements.txt
